export const APP_CONST = {
    LOCAL_STORAGE: {
        SPOTIFY_TOKEN: 'APP_CONST_LOCAL_STORAGE_SPOTIFY_TOKEN',
        SPOTIFY_TOKEN_EXPIRATION_DATE: 'APP_CONST_LOCAL_STORAGE_SPOTIFY_TOKEN_EXPIRATION_DATE',
        SPOTIFY_REFRESH_TOKEN: 'APP_CONST_LOCAL_STORAGE_SPOTIFY_REFRESH_TOKEN',
        SPOTIFY_CURRENT_DEVICE_ID: 'APP_CONST_LOCAL_STORAGE_SPOTIFY_CURRENT_DEVICE_ID'
    },
};